version: '3.8'
services:
  rq-dashboard:
    image: arpitm19/rqworker-docker:0.0.1
    command: rq-dashboard -H rq-server
    ports:
      - 9181:9181

  rq-worker:
    image: arpitm19/rqworker-docker:0.0.1
    command: rq worker -u redis://rq-server:6379 low medium high
    deploy:
      replicas: 3

  rq-server:
    image: redis:alpine
    ports:
      - 6379:6379